### ISSUE TITLE
Problems with input files from PhotoShop

### ISSUE THREAD

**Issue by d0k3** [d0k3/Decrypt9-Menu-GFX-Generator#1] opened 2015-11-28 19:28 UTC
See here: http://gbatemp.net/threads/download-decrypt9-wip-3dsx-launcher-dat.388831/page-60#post-5833603

That problem doesn't happen if the base image was written by IrfanView.

**Comment by Shadowtrance** [comment] 2015-11-28 19:33
As i posted there as well, the issue APPEARS to be that photoshop by default has transparency enabled for exporting png's which is causing the issue. But if the image is exported with transparency off it works fine. :)
No idea if it's different in earlier versions of PS (honestly forget) but that's how it works currently with Photoshop CC 2015 which i use.

**Comment by pixel-stuck** [comment] 2015-11-28 21:07
I think I have solved it, @Shadowtrance try with the latest commit, export your PNGs the old way that you did it and see if it works

**Comment by Shadowtrance** [comment] 2015-11-28 21:21
Seems to be working correctly. Just exported the base image via "Save as..." png which (for some reason unknown to me) gives a bigger png file, about 55kb for this one, and it converts as it should. :)
Also exported it via "Export as..." png > transparency turned ON (checked) and it also works as intended (for another unknown reason to me this base file is only 6kb)... weird.
Safe to say your fix err fixed it. haha :)

**Comment by pixel-stuck** [comment] 2015-11-28 21:27
Cool, I'm closing this then

**Closed as completed by pixel-stuck** 2015-11-28 21:27 UTC
